---
title: "Campaign_Project_Markdown"
output:
  html_document:
    df_print: paged
  pdf_document: default
date: "2025-04-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/alexj/OneDrive/Desktop/Campaign_Project')
```

```{r}
library(dplyr)
library(ggplot2)
library(maps)
library(margins)
library(knitr)
library(tidyverse)
library(kableExtra)
```

```{r}
setwd("C:/Users/alexj/OneDrive/Desktop/Campaign_Project")
```

```{r}
dataset1A <- read.csv("C:/Users/alexj/OneDrive/Desktop/Campaign_Project/data-analyst-take-home/dataset1a.csv")
MailFile <- read.csv("data-analyst-take-home/dataset1b.csv")
HoldoutFile <- read.csv("data-analyst-take-home/dataset1c.csv")
mail_plan <- read.csv("C:/Users/alexj/OneDrive/Desktop/Campaign_Project/data-analyst-take-home/mail_plan.csv")
```

```{r}
#Section 1
#Question 1.1
TransactionFile <- dataset1A %>% 
  filter(str_detect(PrimaryAddress, "^[0-9]"))
#Interesting note: these addresses remove any Armed Forces Europe & Americas (AE & AA)
```

```{r}
#Answer printed for question 1.1
TransactionFile %>% 
  count(PrimaryAddress) %>% 
  nrow()
```


```{r}
TransactionFile %>%
  count(OrderNumber) %>% 
  filter(n > 1)
#Print rows to see repeat order numbers. Blank order numbers are bothering me
```




```{r}
sum(TransactionFile$OrderNumber == "") #Number of NAs in Transaction File; Order Number Column
```


```{r}
#Question 1.2
TransactionFileCleaned <- TransactionFile %>% 
 filter(!str_detect(OrderDate, "^2027")) %>%  #remove incorrect dates
  mutate(OrderDate = as.Date(OrderDate)) %>%  #change OrderDate to from character to Date
  filter(!is.na(OrderDate)) %>%               #remove any NAs in Date column
  filter(OrderNumber != "") %>%               #remove any blank characters in OrderNumber column
  arrange(OrderNumber, OrderDate) %>%         #arrange by OrderNumber then Orderdate
  distinct(OrderNumber, .keep_all = TRUE)     #keep distinct values in OrderNumber that occured first
```




```{r}
#Maybe remove (This has nothing to do with the assignment at least what the question is asking)
#OrderNumbers are NA, counting those
#Wondering if I should randomly assign order numbers to these individuals...probably not
#Regarding Question 1.2
na_orders <- TransactionFile %>%
  filter(OrderNumber == "") %>%
  select(CustomerID)
#Want to put them in one dataframe, would probably ask for corrected data if possible but decided to remove from analysis in this case
```

```{r}
#Question 1.3
TransactionFileCleaned %>% 
  count(State, sort = TRUE)
```

```{r}
#Create visualization for states
TransactionFileCleaned %>%
  count(State, name = "Orders") %>%
  arrange(desc(Orders)) %>%
  top_n(10, Orders) %>%  
  ggplot(aes(x = reorder(State, Orders), y = Orders)) +
  geom_col(fill = "darkgreen") +
  geom_text(aes(label = Orders), hjust = -0.1, size = 3.5) +  
  scale_x_discrete(expand = expansion(mult = c(0, 0.1))) +
  coord_flip() +
  labs(
    title = "Top States by Number of Orders",
    x = "State",
    y = "Orders"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold") 
  )
```


```{r}
#Regarding Question 1.3 (I am curious)
TransactionFileCleaned %>%
  count(State) %>%
  nrow()

```

```{r}
#51 States???? 
sort(unique(TransactionFileCleaned$State))
#Because DC
```


```{r}
#Original contains total, AA, AE that were removed
sort(unique(dataset1A$State))
```
```{r}
#Trying something new

state_orders <- TransactionFileCleaned %>%
  count(State, name = "Orders") #Summarize orders by state abbreviation

state_abbrevs <- data.frame(
  State = state.abb,
  full_name = tolower(state.name))  #Create a lookup table from abbreviations to full state names

state_orders_map <- left_join(state_orders, state_abbrevs, by = "State") #Join to get full state names (required for map_data)
```


```{r}
us_map <- map_data("state") #loads map data and built in map from maps package

map_data_with_orders <- left_join(us_map, state_orders_map, by = c("region" = "full_name"))
```

```{r}
ggplot(map_data_with_orders, aes(long, lat, group = group)) + #In this case it tells Long and Lat
  geom_polygon(aes(fill = Orders), color = "white") + #draws states and fills by orders
  scale_fill_gradient(low = "lightblue", high = "darkblue", na.value = "gray90") + #in this case na value doesnt matter but I think its significant to due for practice purposes
  labs(
    title = "Number of Orders by State",
    fill = "Orders"
  ) +
  theme_void() + #removes background and grid to only show me the map
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold") #and we are now bold and centered
  )
#beautiful
```

```{r}
#Question 1.4
TransactionFileCleaned %>%
  filter(SecondaryAddress != "") %>%
  nrow()
```

```{r}
TransactionFileCleaned %>%
  mutate(HasSecondaryAddress = ifelse(SecondaryAddress != "", "Yes", "No")) %>%
  count(HasSecondaryAddress) %>% #filtered for ggplot to get secondary address results
  ggplot(aes(x = HasSecondaryAddress, y = n, fill = HasSecondaryAddress)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = n), vjust = -0.5, size = 4) +
  labs(
    title = "Orders With vs Without a Secondary Address",
    x = "Has Secondary Address",
    y = "Number of Orders"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
```

```{r}
#Creates dataframe for those who live in Apt or Suite since they are the only two in the data after filtering PO Boxes
AptOrSuiteSummary <- TransactionFileCleaned %>%
  filter(str_starts(SecondaryAddress, "Apt") | str_starts(SecondaryAddress, "Suite")) %>%
  mutate(AddressType = ifelse(str_starts(SecondaryAddress, "Apt"), "Apt", "Suite")) %>%
  count(AddressType)
#Note no AA & AE due to cleaning process
```

```{r}
ggplot(data = AptOrSuiteSummary,mapping = aes(x = AddressType, y = n, fill = AddressType)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = n), vjust = -0.5, size = 4) +
  labs(
    title = "Orders by Secondary Address Type",
    x = "Address Type",
    y = "Number of Orders"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

```


```{r}
#Question 1.5
n_distinct(TransactionFileCleaned$CustomerID)
```
```{r}
#Average number placed based on customer_id (Current year 2021)
nrow(TransactionFileCleaned) / n_distinct(TransactionFileCleaned$CustomerID)
#This is basically 1...bring up in presentation. No need to put this number
```
```{r}
customer_order_counts <- TransactionFileCleaned %>%
  count(CustomerID, name = "Orders")
orders_distribution <- customer_order_counts %>%
  count(Orders, name = "NumCustomers")
#Getting a dataframe with sum of orders and count of CustomerIDS
```


```{r}
ggplot(orders_distribution, aes(x = Orders, y = NumCustomers)) +
  geom_col(fill = "darkgreen") + #I like the green better for this for whatever reason. 
  scale_x_continuous(breaks = c(1, 2)) +  
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  geom_text(aes(label = NumCustomers), vjust = -0.5) +
  labs(
    title = "Quantity of Orders per Customer",
    x = "Number of Orders",
    y = "Number of Customers"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
#Gets the job done better than just 1.00006 or whatever
```


```{r}
duplicate_customers <- TransactionFileCleaned %>%
  count(CustomerID, name = "OrderCount") %>%
  filter(OrderCount > 1)

duplicate_orders_with_addresses <- TransactionFileCleaned %>%
  semi_join(duplicate_customers, by = "CustomerID") %>% 
  arrange(CustomerID)
#Looking at those customers individually
```



```{r}
#Checking which CustomerIDs were not distinct
#Regarding above to check accuracy 
TransactionFile %>%
  count(CustomerID) %>%
  filter(n > 1) %>% 
  nrow()
```

```{r}
#Question 2.1
mail_matches <- semi_join(TransactionFileCleaned, MailFile, by = "FullAddress")
holdout_matches <- semi_join(TransactionFileCleaned, HoldoutFile, by = "FullAddress")
```

```{r}
#Question 2.1 Cont.
n_mail_matches <- nrow(mail_matches)
n_holdout_matches <- nrow(holdout_matches)
n_mail_matches #print our mail matches (i.e. for test 1-3)
n_holdout_matches #print holdout matches
```
```{r}
match_summary <- data.frame(
  Group = c("Mailed", "Holdout"),
  Matches = c(n_mail_matches, n_holdout_matches)
)
#Puts the above results into a data frame
```


```{r}
ggplot(match_summary, aes(x = Group, y = Matches, fill = Group)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = Matches), vjust = -0.1, size = 5) +
  labs(
    title = "Number of Matches by Group",
    x = "Group",
    y = "Number of Matched Orders"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
#Printed table for visual
```


```{r}
#Question 2.2
mail_matches_updated <- inner_join(mail_matches, MailFile, by = "FullAddress")
mail_matches_updated %>%
  count(TestCell, sort = TRUE)
#includes it with TestCells for each test
```

```{r}
mail_matches_updated %>%
  count(TestCell, name = "Matches") %>% #filtering again (this is new to me but so much easier if I feel confident that data is clean properly)
  ggplot(aes(x = Matches, y = reorder(TestCell, Matches), fill = TestCell)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = Matches), hjust = -0.1, size = 5) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.1))) +
  labs(
    title = "Number of Matches by Test Cell",
    x = "Number of Matched Orders",
    y = "Test Cell"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))

```


```{r}
#Question 2.3
orders_per_cell <- mail_matches_updated %>%
  count(TestCell, name = "Orders")
#Get the number of transactions for each test
```

```{r}
mail_totals <- MailFile %>%
  count(TestCell, name = "TotalMailed")
#Total number of mail campaigns for each Test
```


```{r}
#Numbers are off... should be 3822 for mail_plan...change mail plan TestCell 2 Quantity Mailed
mail_plan %>% 
  count(Quantity_Mailed, TestCell)
```

```{r}
#Adjust mail_plan, if needed can run again
if (mail_plan$Quantity_Mailed[mail_plan$TestCell == "TEST2"] != 3822) {
  mail_plan$Quantity_Mailed[mail_plan$TestCell == "TEST2"] <- mail_plan$Quantity_Mailed[mail_plan$TestCell == "TEST2"] + 10
}
#This fixes the error in the mail_plan file. Quantity is actually 3822 not 3812
#Did an if statement because I run my code over and over again and dont want to get the wrong number if I dont use the if statement (i.e. if it is at 3822 I dont want it to change)
mail_plan 
```


```{r}
#Calculate Response Rate
response_rates <- left_join(orders_per_cell, mail_totals, by = "TestCell") %>%
  mutate(ResponseRate = round((Orders / TotalMailed) * 100, 2))
  
response_rates
```

```{r}
#Keeps matches for holdout
holdout_matches <- semi_join(TransactionFileCleaned, HoldoutFile, by = "FullAddress")
```

```{r}
#Other response rates
holdout_orders_count <- nrow(holdout_matches)
holdout_total <- nrow(HoldoutFile)

holdout_response_rate <- round((holdout_orders_count / holdout_total) * 100, 2)
holdout_response_rate
```

```{r}
#Question 2.4
CPO_table <- mail_matches_updated %>%
  group_by(TestCell) %>% #all of these will be done by test (i.e. grouped by)
  summarise(
    Orders = n()) %>% #basically agregating all rows into one through based on what I group by
  left_join(mail_plan, by = "TestCell") %>%
  mutate(CPO = round(Total_Cost / Orders, 2)) %>% #new column 
  select(TestCell, Orders, Total_Cost, CPO) #picking what i need
#done
```


```{r}
Roas_table <- mail_matches_updated %>% 
  group_by(TestCell) %>% #gets it by Testcell
  summarise(
    Revenue = sum(OrderRevenue),
    Orders = n()) %>% 
  left_join(mail_plan, by = "TestCell") %>% 
  mutate(ROAS = round(Revenue / Total_Cost, 2)) #create new column
#ROAS complete
```


```{r}
total_revenue_per_testcell <- mail_matches_updated %>%
  group_by(TestCell) %>%
  summarise(
    Revenue = sum(OrderRevenue)
  )
```

```{r}
#average order value
AOV_table <- Roas_table %>%
  mutate(AOV = round(Revenue / Orders, 2)) %>%
  select(TestCell, Orders, Revenue, AOV)
```


```{r}
#Might remove
RevenuePerPiece_table <- Roas_table %>%
  left_join(mail_totals, by = "TestCell") %>%
  mutate(RevenuePerPiece = round(Revenue / TotalMailed, 2)) %>%
  select(TestCell, TotalMailed, Revenue, RevenuePerPiece)
#Looked up other metrics, this came up. I can calculate so why not
```

```{r}
FirstOrNot <- mail_matches_updated %>% 
  group_by(FirstTimeOrder) %>% 
  summarise(
    Revenue = sum(OrderRevenue),
    Orders = n()
  ) %>% 
  mutate(FirstTimeOrderRate = round(Orders / sum(Orders) * 100, 2)) %>% 
  mutate(FirstTimeOrderRevPer = round(Revenue / sum(Revenue) * 100, 2))
#First time order rate complete
```

```{r}
#This one is for me...I am curious
FirstOrNotbyTest <- mail_matches_updated %>% 
  group_by(TestCell, FirstTimeOrder) %>% 
  summarise(
    Revenue = sum(OrderRevenue),
    Orders = n()
  ) %>% 
  mutate(FirstTimeOrderRateperTest = round(Orders / sum(Orders) * 100, 2))
```

```{r}
HoldoutFirstOrNot <- holdout_matches %>%
  group_by(FirstTimeOrder) %>%
  summarise(
    Revenue = sum(OrderRevenue),
    Orders = n()
  ) %>%
  mutate(
    FirstTimeOrderRate = round(Orders / sum(Orders) * 100, 2),
    FirstTimeOrderRevPer = round(Revenue / sum(Revenue) * 100, 2)
  )
```

```{r}
FirstbyTest <- FirstOrNotbyTest %>%
  filter(FirstTimeOrder == 1)
```


```{r}
mail_summary <- mail_matches_updated %>% #This table is gonna be used for my metrics
  group_by(TestCell) %>%
  summarise(
    Orders = n(),
    Revenue = sum(OrderRevenue)
  ) %>%
  left_join(mail_plan, by = "TestCell") %>%
  mutate(
    ResponseRate = round(Orders / Quantity_Mailed * 100, 2),
    CostPerOrder = round(Total_Cost / Orders, 2),
    ROAS = round(Revenue / Total_Cost, 2),
    AOV = round(Revenue / Orders, 2),
    RevenuePerPiece = round(Revenue / Quantity_Mailed, 2),
    CostPerPiece = round(Total_Cost / Quantity_Mailed, 2)
  ) %>%
  select(TestCell, Quantity_Mailed, Orders, Revenue, Total_Cost, 
         ResponseRate, CostPerOrder, ROAS, AOV, RevenuePerPiece, CostPerPiece) %>%
  arrange(TestCell)
```


```{r}
mail_summary %>% #My table data
  kable("html", caption = "Key Metrics") %>% #html because I'm knitting and I am on windows and caption is just title
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), #striped makes alternating color, hover highlights row when I go over it, condensed makes it tighter, responsive makes it easy for others to read if they have a smaller screen
                full_width = TRUE, font_size = 13) %>% #table is full width across screen and set font size
  row_spec(0, bold = TRUE) #Makes row 0 i.e. my header bold. In this case, my column header
```

```{r}
first_time_summary <- mail_matches_updated %>% #doing same as before just for first time orders
  group_by(TestCell) %>%
  summarise(
    TotalOrders = n(),
    TotalRevenue = sum(OrderRevenue),
    FirstTimeOrders = sum(FirstTimeOrder == 1),
    FirstTimeRevenue = sum(OrderRevenue[FirstTimeOrder == 1])
  ) %>%
  left_join(mail_plan, by = "TestCell") %>% 
  mutate(
    FirstTimeOrderPct = round(FirstTimeOrders / TotalOrders * 100, 2),
    FirstTimeRevenuePct = round(FirstTimeRevenue / TotalRevenue * 100, 2),
    FirstTimeAOV = round(FirstTimeRevenue / FirstTimeOrders, 2),
    FirstTimeROAS = round(FirstTimeRevenue / Total_Cost, 2)
  ) %>%
  select(TestCell, TotalOrders, FirstTimeOrders, FirstTimeOrderPct,
         TotalRevenue, FirstTimeRevenue, FirstTimeRevenuePct, FirstTimeROAS, FirstTimeAOV) %>%
  arrange(TestCell)
```

```{r}
first_time_summary %>% #make the same table as before
  kable("html", caption = "First-Time Buyer Metrics by Test Cell") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = TRUE, font_size = 13) %>%
  row_spec(0, bold = TRUE)
```

```{r}
#Maybe put a box plot to show new acqusition results for visual
mail_matches_updated %>%
  filter(TestCell %in% c("TEST1", "TEST2")) %>%
  ggplot(aes(x = FirstTimeOrder, y = OrderRevenue, fill = FirstTimeOrder)) +
  geom_boxplot() +
  facet_wrap(~ TestCell) +
  labs(
    title = "Order Revenue Distribution by First-Time vs Repeat Buyers",
    x = "First-Time Order",
    y = "Order Revenue ($)",
    fill = "Buyer Type"  
  ) +
  scale_fill_discrete(
    labels = c("Repeat Buyer", "First-Time Buyer")
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

#The box plots are basically similar. Don't see a case of significance where I should use it.
```
```{r}
#Number of successes
success <- c(1393, 468)

#Totaled mailed
trials <- c(5089, 3822)

#2-proportion z-test
prop.test(success, trials)
#Ok so statisically significant in difference regarding response rate
#Z test used because its between to proportions

```


```{r}
#R automatically uses Welch's t-test so thats good to remember because I'm assuming different variance between both
t.test(OrderRevenue ~ TestCell, data = mail_matches_updated %>% 
         filter(TestCell %in% c("TEST1", "TEST2")))
#Not statisically significant in AOV
```


```{r}
#Additional stuff for me continued down
ggplot(TransactionFileCleaned, aes(x = OrderRevenue)) +
  geom_histogram(binwidth = 100, fill = "steelblue", color = "black") +
  scale_x_continuous(breaks = seq(0, 1000, by = 100)) +
  labs(
    title = "Distribution of Order Revenue",
    x = "Order Revenue",
    y = "Frequency"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
#This some fake data man
#This wasnt use, I was just having fun and wanted to see what the distribution was looking like
```
```{r}
#The Dan Ariely Master Class...still a good book
ggplot(mail_matches_updated, aes(x = OrderRevenue)) +
  geom_histogram(binwidth = 100, fill = "steelblue", color = "black") +
  scale_x_continuous(breaks = seq(0, 1000, by = 100)) +
  labs(
    title = "Distribution of Order Revenue with Matches",
    x = "Order Revenue",
    y = "Frequency"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
```
```{r}
#Trying to determine if product is seasonal
#Previous fun project actually gave me the idea to make this
TransactionFileCleaned %>%
  mutate(Month = as.Date(format(OrderDate, "%Y-%m-01"))) %>%  
  group_by(Month) %>%
  summarise(OrderCount = n()) %>%  
  ggplot(aes(x = Month, y = OrderCount)) +
  geom_bar(stat = "identity", fill = "maroon", color = "black") +
  scale_x_date(
    breaks = "1 month",  
    labels = scales::date_format("%b")  
  ) +
  labs(
    title = "Order Count per Month",
    x = "Month",
    y = "Count"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
#Will be used to showcase how I can make other variables out of data I am given and apply these to my analysis
#In this case not effective however, its showcases how I try to determine variables in analysis
```

```{r}
#Curious to see if there is a difference in response rate between first time buyers for each test
response_data_FT <- mail_matches_updated %>%
  mutate(CustomerType = ifelse(FirstTimeOrder == 1, "First-Time Buyers", "Repeat Customers")) %>%
  group_by(TestCell, CustomerType) %>%
  summarise(
    Orders = n()
  ) %>%
  left_join(mail_plan, by = "TestCell") %>%
  mutate(ResponseRate = round((Orders / Quantity_Mailed) * 100, 2)) %>%
  select(TestCell, CustomerType, ResponseRate)

response_data_FT
```


```{r}
response_data_holdout_FT <- holdout_matches %>%
  mutate(CustomerType = ifelse(FirstTimeOrder == 1, "First-Time Buyers", "Repeat Customers")) %>%
  group_by(CustomerType) %>%
  summarise(
    Orders = n()
  ) %>%
  mutate(
    TestCell = "Holdout",
    Quantity_Mailed = nrow(HoldoutFile),
    ResponseRate = round((Orders / Quantity_Mailed) * 100, 2)
  ) %>%
  select(TestCell, CustomerType, ResponseRate)

response_data_holdout_FT
#Yea so basically even which I expected based on all this data but needed to make sure because of new acquisition question
#If holdout response rate for new acquisitions was high for some reason compared to Test 1 then an issue might appear
```




